/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.53
 * Generated at: 2022-02-15 17:07:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.spring.more.users.service.UsersVO;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/MyStudy/70_spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/moremore/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1635183043313L));
    _jspx_dependants.put("/homeHeader.jsp", Long.valueOf(1637508896000L));
    _jspx_dependants.put("/homeFooter.jsp", Long.valueOf(1637387332000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.spring.more.users.service.UsersVO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("	<title>moremore - 크라우드 펀딩</title>\n");
      out.write("	<meta charset=\"UTF-8\" />\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, maximum-scale=1.0, minimum-scale=1, user-scalable=yes,initial-scale=1.0\" />\n");
      out.write("	<link rel=\"shortcut icon\" href=\"#\">\n");
      out.write("   	<link rel=\"stylesheet\" href=\"resources/css/styles.css\" type=\"text/css\" />\n");
      out.write("   	<!-- Link Swiper's CSS -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://unpkg.com/swiper/swiper-bundle.min.css\"/>\n");
      out.write("   	<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\n");
      out.write("   	<!-- Swiper's Style -->\n");
      out.write("   	<style>\n");
      out.write("      html, body {\n");
      out.write("        position: relative;]\n");
      out.write("        height: 100%;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      body {\n");
      out.write("        background: #eee;\n");
      out.write("        color: #000;\n");
      out.write("        margin: 0;\n");
      out.write("        padding: 0;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      .swiper {\n");
      out.write("        width: 100%;\n");
      out.write("        height: 100%;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      .swiper-slide {\n");
      out.write("        text-align: center;\n");
      out.write("        font-size: 18px;\n");
      out.write("        background: #fff;\n");
      out.write("\n");
      out.write("        /* Center slide text vertically */\n");
      out.write("        display: -webkit-box;\n");
      out.write("        display: -ms-flexbox;\n");
      out.write("        display: -webkit-flex;\n");
      out.write("        display: flex;\n");
      out.write("        -webkit-box-pack: center;\n");
      out.write("        -ms-flex-pack: center;\n");
      out.write("        -webkit-justify-content: center;\n");
      out.write("        justify-content: center;\n");
      out.write("        -webkit-box-align: center;\n");
      out.write("        -ms-flex-align: center;\n");
      out.write("        -webkit-align-items: center;\n");
      out.write("        align-items: center;\n");
      out.write("        height: 400px;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      .swiper-slide img {\n");
      out.write("        display: block;\n");
      out.write("        width: 100%;\n");
      out.write("        height: 100%;\n");
      out.write("        object-fit: cover;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      .swiper {\n");
      out.write("        margin-left: auto;\n");
      out.write("        margin-right: auto;\n");
      out.write("      }\n");
      out.write("    </style>\n");
      out.write("    <script>\n");
      out.write("      $(document).ready(function () {\n");
      out.write("        console.log(\"home 실행\");\n");
      out.write("        \n");
      out.write("        var link = document.location.href;\n");
      out.write("        console.log(\"link : \" + link );\n");
      out.write("        \n");
      out.write("        getJSONBestItemList();\n");
      out.write("        getJSONRecommendItemList();\n");
      out.write("        getJSONHashTagList(); \n");
      out.write("        \n");
      out.write("          $(\"#hashTagBeauty\").on(\"click\", function () {\n");
      out.write("            console.log(\"hashTagBeauty 실행~~\");\n");
      out.write("        	  var cate = \"cate=1\";\n");
      out.write("        	  getJSONHashTagItemCateList(cate);\n");
      out.write("          })\n");
      out.write("          \n");
      out.write("    	 	$(\"#hashTagAnimal\").on(\"click\", function () {\n");
      out.write("            console.log(\"hashTagAnimal 실행~~\");\n");
      out.write("    		  var cate = \"cate=2\";\n");
      out.write("    		  getJSONHashTagItemCateList(cate);\n");
      out.write("          })\n");
      out.write("          \n");
      out.write("    	  	$(\"#hashTagFood\").on(\"click\", function () {\n");
      out.write("            console.log(\"hashTagFood 실행~~\");\n");
      out.write("    		  var cate = \"cate=3\";\n");
      out.write("    		  getJSONHashTagItemCateList(cate);\n");
      out.write("    	  	})\n");
      out.write("        \n");
      out.write("      });\n");
      out.write("      \n");
      out.write("      function getJSONBestItemList() {\n");
      out.write("        console.log(\">> getJSONBestItemList() 실행~~~\");\n");
      out.write("\n");
      out.write("        $.ajax(\"bestItemList.do\", {\n");
      out.write("          type: \"post\",\n");
      out.write("          dataType: \"json\", \n");
      out.write("          contentType: \"application/json; UTF-8;\",\n");
      out.write("       \n");
      out.write("          success: function (data) {\n");
      out.write("        	  const list = data[\"projectList\"];\n");
      out.write("        	  var result = data.json;\n");
      out.write("              console.log(\"getJSONHome 함수 실행~~~\");\n");
      out.write("              console.log(data);\n");
      out.write("              console.log(list);\n");
      out.write("\n");
      out.write("              console.log(JSON.stringify(data))\n");
      out.write("              console.log(result);\n");
      out.write("            \n");
      out.write("            // 데이터 넣기 전 공백으로 초기화 \n");
      out.write("            $(\"#projectList\").html(\"\");\n");
      out.write("            \n");
      out.write("            var result = \"\";\n");
      out.write("            $.each(data, function(index, item){\n");
      out.write("	          	 console.log(index + \" \" + item.pro_stitle);\n");
      out.write("	          	 var proGprice = item.pro_gprice * 1;\n");
      out.write("	          	 var paymentPrice = item.pro_status * 1;\n");
      out.write("	         	 var pro_percent = Math.round((paymentPrice / proGprice) * 100);\n");
      out.write("	          	 console.log(\"paymentPrice : \" + paymentPrice);\n");
      out.write("	          	 console.log(\"proGprice : \" + proGprice);\n");
      out.write("	          	 console.log(\"pro_percent : \" + pro_percent);\n");
      out.write("	             result += \"<li class='projectCardItem' onclick='go_project(\"+item.pro_no+\")'>\";\n");
      out.write("	             result += \"<div class='projectThumbnailWrapper'>\";\n");
      out.write("	             result += \"<img class='projectThumbnail' src='\" + item.pro_thumbnail_path + \"'></div>\";\n");
      out.write("	             result += \"<div class='projectContent'>\";\n");
      out.write("	             result += \"<p>\" + item.pro_stitle + \"</p>\";\n");
      out.write("	             result += \"<span class='greyColor' style='color:#00a2a2;'>\" + pro_percent + \"</span>\";\n");
      out.write("	             result += \"<span class='projectAchievementRate' style='color:#999DA3;'> %달성</span>\";\n");
      out.write("	             result += \"<span class='greyColor floatRight' style='color:#286DB4;'>\" + item.pro_close_dt + \"일 남음</span></div></li>\";\n");
      out.write("        	});\n");
      out.write("            console.log(\"result : \" + result);\n");
      out.write("            $(\"#projectList\").html(result);\n");
      out.write("            \n");
      out.write("          },\n");
      out.write("          error: function (request, status, error) {\n");
      out.write("        	 \n");
      out.write("            alert(\n");
      out.write("              \"Ajax 처리 실패, \" + \"\\n\" +\n");
      out.write("                \"code : \" + request.status + \"\\n\" +\n");
      out.write("                \"message : \" + request.responseText + \"\\n\" +\n");
      out.write("                \"error : \" + error\n");
      out.write("            );\n");
      out.write("          },\n");
      out.write("        });\n");
      out.write("      }\n");
      out.write("      \n");
      out.write("      function getJSONRecommendItemList() {\n");
      out.write("          console.log(\">> getJSONRecommendItemList() 실행~~~\");\n");
      out.write("\n");
      out.write("          $.ajax(\"recommendItemList.do\", {\n");
      out.write("            type: \"post\",\n");
      out.write("            dataType: \"json\", \n");
      out.write("            contentType: \"application/json; UTF-8;\",\n");
      out.write("         \n");
      out.write("            success: function (data) {\n");
      out.write("          	  var result = data.json;\n");
      out.write("                console.log(\"함수 실행~~~\");\n");
      out.write("              \n");
      out.write("              // 데이터 넣기 전 공백으로 초기화 \n");
      out.write("              $(\"#projectRecommendList\").html(\"\");\n");
      out.write("              \n");
      out.write("              var result = \"\";\n");
      out.write("              $.each(data, function(index, item){\n");
      out.write(" 	          	 console.log(index + \" \" + item.pro_stitle);\n");
      out.write(" 	          	 var proGprice = item.pro_gprice * 1;\n");
      out.write(" 	          	 var paymentPrice = item.pro_status * 1;\n");
      out.write(" 	         	 var pro_percent = Math.round((paymentPrice / proGprice) * 100);\n");
      out.write(" 	          	 console.log(\"paymentPrice : \" + paymentPrice);\n");
      out.write(" 	          	 console.log(\"proGprice : \" + proGprice);\n");
      out.write(" 	          	 console.log(\"pro_percent : \" + pro_percent);\n");
      out.write(" 	             result += \"<li class='projectCardItem' onclick='go_project(\"+item.pro_no+\")'>\";\n");
      out.write(" 	             result += \"<div class='projectThumbnailWrapper'>\";\n");
      out.write(" 	             result += \"<img class='projectThumbnail' src='\" + item.pro_thumbnail_path + \"'></div>\";\n");
      out.write(" 	             result += \"<div class='projectContent'>\";\n");
      out.write(" 	             result += \"<p>\" + item.pro_stitle + \"</p>\";\n");
      out.write(" 	             result += \"<span class='greyColor' style='color:#00a2a2;'>\" + pro_percent + \"</span>\";\n");
      out.write(" 	             result += \"<span class='projectAchievementRate' style='color:#999DA3;'> %달성</span>\";\n");
      out.write(" 	             result += \"<span class='greyColor floatRight' style='color:#286DB4;'>\" + item.pro_close_dt + \"일 남음</span></div></li>\";\n");
      out.write("          	});\n");
      out.write("              console.log(\"result : \" + result);\n");
      out.write("              $(\"#projectRecommendList\").html(result);\n");
      out.write("              \n");
      out.write("            },\n");
      out.write("            error: function (request, status, error) {\n");
      out.write("          	 \n");
      out.write("              alert(\n");
      out.write("                \"Ajax 처리 실패, \" + \"\\n\" +\n");
      out.write("                  \"code : \" + request.status + \"\\n\" +\n");
      out.write("                  \"message : \" + request.responseText + \"\\n\" +\n");
      out.write("                  \"error : \" + error\n");
      out.write("              );\n");
      out.write("            },\n");
      out.write("          });\n");
      out.write("        }      \n");
      out.write("      \n");
      out.write("      // 메인페이지에서 해시태그 공간 기본 상태\n");
      out.write("      function getJSONHashTagList() {\n");
      out.write("          console.log(\">> hashTagItemList() 실행~~~\");\n");
      out.write("\n");
      out.write("          $.ajax(\"hashTagItemList.do\", {\n");
      out.write("            type: \"post\",\n");
      out.write("            dataType: \"json\", \n");
      out.write("            contentType: \"application/json; UTF-8;\",\n");
      out.write("         \n");
      out.write("            success: function (data) {\n");
      out.write("          	  var result = data.json;\n");
      out.write("                console.log(\"함수 실행~~~\");\n");
      out.write("              \n");
      out.write("              // 데이터 넣기 전 공백으로 초기화 \n");
      out.write("              $(\"#projectHashTagList\").html(\"\");\n");
      out.write("              \n");
      out.write("              var result = \"\";\n");
      out.write("              $.each(data, function(index, item){\n");
      out.write(" 	          	 console.log(index + \" \" + item.pro_stitle);\n");
      out.write(" 	          	 var proGprice = item.pro_gprice * 1;\n");
      out.write(" 	          	 var paymentPrice = item.pro_status * 1;\n");
      out.write(" 	         	 var pro_percent = Math.round((paymentPrice / proGprice) * 100);\n");
      out.write(" 	          	 console.log(\"paymentPrice : \" + paymentPrice);\n");
      out.write(" 	          	 console.log(\"proGprice : \" + proGprice);\n");
      out.write(" 	          	 console.log(\"pro_percent : \" + pro_percent);\n");
      out.write(" 	             result += \"<li class='projectCardItem' onclick='go_project(\"+item.pro_no+\")'>\";\n");
      out.write(" 	             result += \"<div class='projectThumbnailWrapper'>\";\n");
      out.write(" 	             result += \"<img class='projectThumbnail' src='\" + item.pro_thumbnail_path + \"'></div>\";\n");
      out.write(" 	             result += \"<div class='projectContent'>\";\n");
      out.write(" 	             result += \"<p>\" + item.pro_stitle + \"</p>\";\n");
      out.write(" 	             result += \"<span class='greyColor' style='color:#00a2a2;'>\" + pro_percent + \"</span>\";\n");
      out.write(" 	             result += \"<span class='projectAchievementRate' style='color:#999DA3;'> %달성</span>\";\n");
      out.write(" 	             result += \"<span class='greyColor floatRight' style='color:#286DB4;'>\" + item.pro_close_dt + \"일 남음</span></div></li>\";\n");
      out.write("          	});\n");
      out.write("              console.log(\"result : \" + result);\n");
      out.write("              $(\"#projectHashTagList\").html(result);\n");
      out.write("              \n");
      out.write("            },\n");
      out.write("            error: function (request, status, error) {\n");
      out.write("          	 \n");
      out.write("              alert(\n");
      out.write("                \"Ajax 처리 실패, \" + \"\\n\" +\n");
      out.write("                  \"code : \" + request.status + \"\\n\" +\n");
      out.write("                  \"message : \" + request.responseText + \"\\n\" +\n");
      out.write("                  \"error : \" + error\n");
      out.write("              );\n");
      out.write("            },\n");
      out.write("          });\n");
      out.write("        }\n");
      out.write("      \n");
      out.write("	   // 해시태그 버튼 클릭 시 변경 상태\n");
      out.write("	      function getJSONHashTagItemCateList(cate) {\n");
      out.write("	          console.log(\">> getJSONHashTagItemCateList() 실행~~~\");\n");
      out.write("	          console.log(\"cate : \" + cate);\n");
      out.write("	\n");
      out.write("	          $.ajax(\"hashTagItemCateList.do?\" + cate, {\n");
      out.write("	            type: \"get\",\n");
      out.write("	            dataType: \"json\", \n");
      out.write("	            contentType: \"application/json; UTF-8;\",\n");
      out.write("	         \n");
      out.write("	            success: function (data) {\n");
      out.write("	          	  var result = data.json;\n");
      out.write("	                console.log(\"함수 실행~~~\");\n");
      out.write("	              \n");
      out.write("	              // 데이터 넣기 전 공백으로 초기화 \n");
      out.write("	              $(\"#projectHashTagList\").html(\"\");\n");
      out.write("	              \n");
      out.write("	              var result = \"\";\n");
      out.write("	              $.each(data, function(index, item){\n");
      out.write("	 	          	 console.log(index + \" \" + item.pro_stitle);\n");
      out.write("	 	          	 var proGprice = item.pro_gprice * 1;\n");
      out.write("	 	          	 var paymentPrice = item.pro_status * 1;\n");
      out.write("	 	         	 var pro_percent = Math.round((paymentPrice / proGprice) * 100);\n");
      out.write("	 	          	 console.log(\"paymentPrice : \" + paymentPrice);\n");
      out.write("	 	          	 console.log(\"proGprice : \" + proGprice);\n");
      out.write("	 	          	 console.log(\"pro_percent : \" + pro_percent);\n");
      out.write("	 	             result += \"<li class='projectCardItem' onclick='go_project(\"+item.pro_no+\")'>\";\n");
      out.write("	 	             result += \"<div class='projectThumbnailWrapper'>\";\n");
      out.write("	 	             result += \"<img class='projectThumbnail' src='\" + item.pro_thumbnail_path + \"'></div>\";\n");
      out.write("	 	             result += \"<div class='projectContent'>\";\n");
      out.write("	 	             result += \"<p>\" + item.pro_stitle + \"</p>\";\n");
      out.write("	 	             result += \"<span class='greyColor' style='color:#00a2a2;'>\" + pro_percent + \"</span>\";\n");
      out.write("	 	             result += \"<span class='projectAchievementRate' style='color:#999DA3;'> %달성</span>\";\n");
      out.write("	 	             result += \"<span class='greyColor floatRight' style='color:#286DB4;'>\" + item.pro_close_dt + \"일 남음</span></div></li>\";\n");
      out.write("	          	});\n");
      out.write("	              console.log(\"result : \" + result);\n");
      out.write("	              $(\"#projectHashTagList\").html(result);\n");
      out.write("	              \n");
      out.write("	            },\n");
      out.write("	            error: function (request, status, error, data) {\n");
      out.write("	          	 \n");
      out.write("	              alert(\n");
      out.write("	                \"Ajax 처리 실패, \" + \"\\n\" +\n");
      out.write("	                  \"code : \" + request.status + \"\\n\" +\n");
      out.write("	                  \"message : \" + request.responseText + \"\\n\" +\n");
      out.write("	                  \"error : \" + error +\n");
      out.write("	                  \"data : \" + data\n");
      out.write("	              );\n");
      out.write("	            },\n");
      out.write("	          });\n");
      out.write("	        }\n");
      out.write("\n");
      out.write("	   go_project = (e) => {\n");
      out.write("		   location.href = \"project/goProjectStart.do?pro_no=\"+e;\n");
      out.write("	   }\n");
      out.write("    </script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	");
      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("    \n");
      out.write("	<header class=\"header-wrapper greenColor\">\n");
      out.write("		<div class=\"header-contaniner\" id=\"headerContainerId\">\n");
      out.write("			<h4 class=\"headerLogo\">\n");
      out.write("				<a href=\"home.jsp\" class=\"headerLogo purple\">\n");
      out.write("				<span ><img src=\"resources/images/logo1.png\"></span>\n");
      out.write("				</a>\n");
      out.write("			</h4>\n");
      out.write("			<div class=\"headerMenuArea\">\n");
      out.write("				<ul class=\"headerMenu\">\n");
      out.write("					<li class=\"headerMenuItem middleSize\" id=\"headerMenuFunding\"><a href=\"fundingProjectList.jsp\">펀딩하기</a></li>\n");
      out.write("					<!-- <li class=\"headerMenuItem middleSize\" id=\"headerMenuBuy\"><a href=#>구매하기</a></li> -->\n");
      out.write("					<li class=\"headerMenuItem middleSize\" id=\"headerMenuGuide\"><a href=\"notice.do\" class=\"headerMenuHidden\">이용가이드</a></li>\n");
      out.write("					<li class=\"headerMenuItem moreItem\" id=\"headerMenuMoreItem\"><a href=# class=\"headerMenuHidden\">더보기</a></li>\n");
      out.write("					<li class=\"headerMenuItem middleSize\" id=\"headerMenuProjectBtnList\"><a href=\"fromHomeToAdmin.jsp\" id=\"headerMenuProjectBtn\" class=\"purple\">프로젝트 신청</a></li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"headerUtil\">\n");
      out.write("				<form name=\"headerSearch\" action=\"searchFunding.do\" method=\"get\">\n");
      out.write("					<input type=\"search\" name=\"pro_stitle\" class=\"searchBar\" placeholder=\"프로젝트 검색하기\"/>\n");
      out.write("				</form>\n");
      out.write("				<!-- 비로그인 시 출력 -->\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("  \n");
      out.write("				<!-- 로그인 시 출력 -->\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</header>");
      out.write("\n");
      out.write("	<!-- <div class=\"lightPink\" id=\"headerSlide\"> -->\n");
      out.write("	<div>\n");
      out.write("<!-- 		<img id=\"headerSlide\" src=\"https://image.hago.kr/mall/display/mmon-templates/6/51/689/pc_image_1.jpg?ut=2021-11-05 18:08:53\">\n");
      out.write(" -->		<!-- <img id=\"headerSlide\" src=\"https://cdn.wadiz.kr/ft/images/green001/2021/1029/20211029103938521_4215.png/wadiz/optimize\"> -->\n");
      out.write("	<!-- Swiper -->\n");
      out.write("    <div class=\"swiper mySwiper\">\n");
      out.write("      <div class=\"swiper-wrapper\">\n");
      out.write("        <div class=\"swiper-slide\"><img class=\"headerSlide\" src=\"https://image.hago.kr/mall/display/mmon-templates/6/51/689/pc_image_1.jpg?ut=2021-11-05 18:08:53\"></div>\n");
      out.write("        <div class=\"swiper-slide\"><img class=\"headerSlide\" src=\"https://image.hago.kr/mall/display/mmon-templates/6/51/844/pc_image_1.jpg?ut=2021-11-11 18:00:31\"></div>\n");
      out.write("        <div class=\"swiper-slide\"><img class=\"headerSlide\" src=\"https://image.hago.kr/mall/display/mmon-templates/6/51/843/pc_image_1.jpg?ut=2021-11-11 18:00:31\"></div>\n");
      out.write("        <div class=\"swiper-slide\"><img class=\"headerSlide\" src=\"https://image.hago.kr/mall/display/mmon-templates/6/51/590/pc_image_1.jpg?ut=2021-11-11 18:00:31\"></div>\n");
      out.write("        <div class=\"swiper-slide\"><img class=\"headerSlide\" src=\"https://image-se.ycrowdy.com/20211022/CROWDY_0_202110222242110129_gaeul.png\"></div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"swiper-button-next\" style=\"color:grey;\"></div>\n");
      out.write("      <div class=\"swiper-button-prev\" style=\"color:grey;\"></div>\n");
      out.write("      <div class=\"swiper-pagination\"></div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Swiper JS -->\n");
      out.write("    <script src=\"https://unpkg.com/swiper/swiper-bundle.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Initialize Swiper -->\n");
      out.write("    <script>\n");
      out.write("      var swiper = new Swiper(\".mySwiper\", {\n");
      out.write("        slidesPerView: 1,\n");
      out.write("        spaceBetween: 30,\n");
      out.write("        loop: true,\n");
      out.write("        pagination: {\n");
      out.write("          el: \".swiper-pagination\",\n");
      out.write("          clickable: true,\n");
      out.write("        },\n");
      out.write("        navigation: {\n");
      out.write("          nextEl: \".swiper-button-next\",\n");
      out.write("          prevEl: \".swiper-button-prev\",\n");
      out.write("        },\n");
      out.write("      });\n");
      out.write("    </script>\n");
      out.write("	\n");
      out.write("	</div>\n");
      out.write("	<div id=\"containerWrapper\">\n");
      out.write("		<div class=\"container\" style=\"margin-top: 20px;\">\n");
      out.write("			<div class=\"projectInfoBannerHome\">\n");
      out.write("				<div class=\"projectInfoBannerMenuWrapper\">\n");
      out.write("					<ul class=\"projectInfoBannerMenu centerItemTop\">\n");
      out.write("						<li class=\"projectInfoItemTop\" style=\"margin-right: 120px\"><a href=\"#\">206</a></li>\n");
      out.write("						<li class=\"projectInfoItemTop\" style=\"margin-right: 90px\"><a href=\"#\">303,723,400</a></li>\n");
      out.write("						<li class=\"projectInfoItemTop\"><a href=\"#\">5,679</a></li>\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"projectInfoBannerMenuWrapper\">\n");
      out.write("				<ul class=\"projectInfoBannerMenu centerItemBottom\">\n");
      out.write("					<li class=\"projectInfoItemBottom\"><a href=\"#\">총 펀딩 프로젝트</a></li>\n");
      out.write("					<li class=\"projectInfoItemBottom\"><a href=\"#\">총 펀딩 금액</a></li>\n");
      out.write("					<li class=\"projectInfoItemBottom\"><a href=\"#\">참여 서포터 수</a></li>\n");
      out.write("				</ul>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div>\n");
      out.write("				<h3 class=\"mainMenuTitle\" id=\"bestProjectTitle\">인기 프로젝트</a></h3>\n");
      out.write("				<div class=\"projectWrapper\">\n");
      out.write("					<ul id=\"projectList\" class=\"projectCard\">\n");
      out.write("					</ul>\n");
      out.write("				</div>				\n");
      out.write("			</div>\n");
      out.write("			<div class=\"\">\n");
      out.write("				<h3 style=\"margin-top:120px;\" class=\"mainMenuTitle\" id=\"recommendProjectTitle\">이 프로젝트 어때요?</h3>\n");
      out.write("				<div class=\"projectWrapper\">\n");
      out.write("					<ul id=\"projectRecommendList\" class=\"projectCard\">\n");
      out.write("					</ul>\n");
      out.write("				</div>	\n");
      out.write("			</div>\n");
      out.write("			<div class=\"projectStatusBanner\">\n");
      out.write("				<div style=\"display:flex;\">\n");
      out.write("					<div>\n");
      out.write("						<ul>\n");
      out.write("							<li style=\"font-size: 20px; margin-right: 200px; margin-left: 200px;\">오늘 이만큼 참여하셨어요!</li>\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("					<div>\n");
      out.write("						<ul style=\"display:flex; font-size: 15px; margin-top: 5px;\">\n");
      out.write("							<li style=\"padding-right: 20px; padding-top: 5px;\">총 참여</li>\n");
      out.write("							<li style=\"padding-right: 20px; font-size:23px; color:#F4C539; font-weight: 800;\">4,231명</li>\n");
      out.write("							<li style=\"padding-right: 20px; padding-top: 5px;\">총 금액</li>\n");
      out.write("							<li style=\"padding-right: 20px; font-size:23px; color:#F4C539; font-weight: 800;\">303,723,400원</li>\n");
      out.write("						</ul>\n");
      out.write("						<ul style=\"display:flex; font-size: 15px;\">\n");
      out.write("							<li style=\"padding-right: 20px; padding-top: 5px;\">오늘의 참여</li>\n");
      out.write("							<li style=\"padding-right: 20px; font-size:23px; color:#F4C539; font-weight: 800;\">23명</li>\n");
      out.write("							<li style=\"padding-right: 20px; padding-top: 5px;\">오늘 참여금액</li>\n");
      out.write("							<li style=\"padding-right: 20px; font-size:23px; color:#F4C539; font-weight: 800;\">2,234,100원</li>\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"containerHashTagArea\">\n");
      out.write("				<ul class=\"containerHashTagMenu\">\n");
      out.write("					<li class=\"hashTagBtn\" id=\"hashTagBeauty\">#뷰티</li>\n");
      out.write("					<li class=\"hashTagBtn\" id=\"hashTagAnimal\">#반려동물</li>\n");
      out.write("					<li class=\"hashTagBtn\" id=\"hashTagFood\">#푸드</li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"projectWrapper\">\n");
      out.write("				<ul id=\"projectHashTagList\" class=\"projectCard\">\n");
      out.write("				</ul>\n");
      out.write("			</div>	\n");
      out.write("			<div class=\"projectStartBanner\" >\n");
      out.write("				<p style=\"color:white;\">좋은 아이디어가 있으신가요?</p>\n");
      out.write("				<h4 style=\"color:white;\">지금바로 펀딩 프로젝트를 만들어서 참여해보세요!</h4> \n");
      out.write("				<button class=\"IndigoBtn\" type=\"button\" onclick=\"go_funding()\" style=\"margin-top: 20px;\">바로 가기</button>\n");
      out.write("			</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	");
      out.write("\n");
      out.write("	<footer id=\"footer\">\n");
      out.write("      <div class=\"infoArea\">\n");
      out.write("        <div class=\"footerMenuArea\">\n");
      out.write("          <ul class=\"footerMenu\">\n");
      out.write("            <li>회사소개</li>\n");
      out.write("            <li>이용약관</li>\n");
      out.write("            <li>개인정보처리방침</li>\n");
      out.write("          </ul>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"footerArea\">\n");
      out.write("        <img src=\"resources/images/logo1.png\" style=\"display:inline; width : 150px; margin-left: 200px;\" />\n");
      out.write("          <div class=\"footerRight\">\n");
      out.write("            <ul class=footerList>\n");
      out.write("              <li><h4>모아모아</h4></li> \n");
      out.write("              <li>대표이사 : 모아모아</li>\n");
      out.write("              <li>\n");
      out.write("                주소 (우) 010101 서울특별시 비트로 999-1 비트캠프\n");
      out.write("              </li>\n");
      out.write("              <li>\n");
      out.write("                고객지원센터 : 1588-1111 \n");
      out.write("              </li>\n");
      out.write("              <li class=\"COPYRIGHT\">COPYRIGHTⓒ moremore</li>\n");
      out.write("            </ul>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </footer>");
      out.write("\n");
      out.write("</body>\n");
      out.write("<script>\n");
      out.write("	go_funding = () => {\n");
      out.write("		location.href=\"fromHomeToAdmin.jsp\";\n");
      out.write("	}\n");
      out.write("</script>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /homeHeader.jsp(27,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empty sessionScope.loginUsers }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("					<button type=\"button\" class=\"noneBtn\" onclick=\"javascript:location.href='login.jsp'\">로그인</button>\n");
          out.write("					<button type=\"button\" class=\"noneBtn\" onclick=\"javascript:location.href='joinMembership.jsp'\">회원가입</button>\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /homeHeader.jsp(32,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ !empty sessionScope.loginUsers }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("		            <button type=\"button\" class=\"myPageBtn\" onclick=\"javascript:location.href='userInfo.jsp'\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ loginUsers.user_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님</button>\n");
          out.write("					<button type=\"button\" class=\"noneBtn\" onclick=\"javascript:location.href='logout.do'\">로그아웃</button>\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
