/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.53
 * Generated at: 2022-02-15 17:18:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class siteAdminHome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/siteAdminHeader.jsp", Long.valueOf(1637633663000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

session.setAttribute("admin",21 );	

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js\"></script>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>사이트 관리자 메인페이지 | more more</title>\n");
      out.write("   	<link rel=\"stylesheet\" href=\"resources/css/styles.css\" type=\"text/css\" />\n");
      out.write("</head>\n");
      out.write("<script>\n");
      out.write("		$.ajax(\"getAdminMain.do\", {\n");
      out.write("			type: \"get\",\n");
      out.write("			dataType: \"json\",\n");
      out.write("			success: function(data){\n");
      out.write("				console.log(data);\n");
      out.write("				console.log(data.today[0].COUNT);\n");
      out.write("				//document.querySelector(\".c1\").href += data.cntTot;\n");
      out.write("				document.querySelector(\".New\").innerHTML += data.cntNew+\"명\";\n");
      out.write("				document.querySelector(\".Tot\").innerHTML += data.cntTot+\"명\";\n");
      out.write("				document.querySelector(\".Out\").innerHTML += data.cntOut+\"명\";\n");
      out.write("				document.querySelector(\".ingProj\").innerHTML += data.ingProj+\"건\";\n");
      out.write("				document.querySelector(\".waitProj\").innerHTML += data.waitProj+\"건\";\n");
      out.write("				document.querySelector(\".endProj\").innerHTML += data.endProj+\"건\";\n");
      out.write("				document.querySelector(\".cntPayment\").innerHTML += data.cntPayment+\"건\";\n");
      out.write("				document.querySelector(\".cntSale\").innerHTML += data.cntSale.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, ',')+\"원\"; //수수료 20%\n");
      out.write("				document.querySelector(\".cntCancel\").innerHTML += data.cntCancel+\"건\";\n");
      out.write("				document.querySelector(\".todaySale\").innerHTML += data.today[0].TODAYSUM.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, ',')+\"원\";\n");
      out.write("				document.querySelector(\".todayCnt\").innerHTML += data.today[0].COUNT+\"건\";\n");
      out.write("				\n");
      out.write("			},\n");
      out.write("			error: function(){\n");
      out.write("				alert(\"실패!\");\n");
      out.write("			}\n");
      out.write("		});\n");
      out.write("	\n");
      out.write("</script>\n");
      out.write("<style>\n");
      out.write("	.adminContainerContent{\n");
      out.write("		\n");
      out.write("	}\n");
      out.write("	.adminContainerContent div{\n");
      out.write("		border-radius: 14px;\n");
      out.write("	    box-shadow: 3px 3px 6px 0 rgb(33 37 41 / 13%);\n");
      out.write("	    background-color: #fff;\n");
      out.write("	    margin-right: 50px;\n");
      out.write("	    margin-top: 35px;\n");
      out.write("	    margin-left: 35px;\n");
      out.write("	    width: 350px;\n");
      out.write("	    height: 250px;	 \n");
      out.write("	    font-size: 20px;\n");
      out.write("	    text-align: center;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	#title{\n");
      out.write("		margin-bottom: 20px;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.todayBox{\n");
      out.write("		border: 1px solid #dde2e6;\n");
      out.write("    	width: 400px;\n");
      out.write("	    height: 300px;\n");
      out.write("	    margin-top: 60px;\n");
      out.write("	    margin-left: 40px;\n");
      out.write("	    border-radius: 14px;\n");
      out.write("	    background-color: #fff;\n");
      out.write("	    box-shadow: 3px 3px 6px rgb(33 37 41 / 13%);\n");
      out.write("	    text-align: center;\n");
      out.write("	    \n");
      out.write("	}\n");
      out.write("	ul{\n");
      out.write("		padding-left:0;\n");
      out.write("		margin-top: 50px;\n");
      out.write("	}\n");
      out.write("	.all{\n");
      out.write("		position: relative;\n");
      out.write("		width: 700px;\n");
      out.write("	    border: 1px solid #dde2e6;\n");
      out.write("	    border-radius: 14px;\n");
      out.write("	    transform: translate(78%,-77.5%);\n");
      out.write("	    background-color: white;\n");
      out.write("	    box-shadow: 3px 3px 6px rgb(33 37 41 / 13%);\n");
      out.write("	}\n");
      out.write("	.todaytitle{\n");
      out.write("		font-size: 24px;\n");
      out.write("	}\n");
      out.write("	.todaySale{\n");
      out.write("		color: #286DB4;\n");
      out.write("	    font-weight: bold;\n");
      out.write("	    font-size: 50px;\n");
      out.write("	    margin-top: 40px;\n");
      out.write("	    margin-bottom: 20px;\n");
      out.write("	}\n");
      out.write("	.todayCnt{\n");
      out.write("		color: darkgray;\n");
      out.write("		margin-top: 40px;\n");
      out.write("	}\n");
      out.write("	.requestProj li{\n");
      out.write("		float: left;\n");
      out.write("		margin-right: 35px;\n");
      out.write("		margin-top: 38px;\n");
      out.write("	}\n");
      out.write("	.listPro\n");
      out.write("	{\n");
      out.write("		margin-top: 15px;\n");
      out.write("	}\n");
      out.write("	.request{\n");
      out.write("		width: 404px;\n");
      out.write("	    border: 1px solid #dde2e6;\n");
      out.write("	    height: 300px;\n");
      out.write("	    border-radius: 14px;\n");
      out.write("	    box-shadow: 3px 3px 6px rgb(33 37 41 / 13%);\n");
      out.write("	    transform: translate(9.5%,-140%);\n");
      out.write("	    background-color: white;\n");
      out.write("	    \n");
      out.write("	}\n");
      out.write("	.requestProj{\n");
      out.write("		margin-left: 30px;\n");
      out.write("    	font-size: 15px;\n");
      out.write("	}\n");
      out.write("	.margin_fake_data li \n");
      out.write("	{\n");
      out.write("		margin-top: 8px;\n");
      out.write("	}\n");
      out.write("	#title_box\n");
      out.write("	{\n");
      out.write("		position: absolute;\n");
      out.write("	    left: 100px;\n");
      out.write("	    top: 10px;\n");
      out.write("	    margin-top: 21px;\n");
      out.write("	    font-size: 22px;\n");
      out.write("	}\n");
      out.write("	.chartTitle\n");
      out.write("	{\n");
      out.write("		position: relative;\n");
      out.write("    	right: -26px;\n");
      out.write("	}\n");
      out.write("	.adminLocationArea\n");
      out.write("	{\n");
      out.write("		width: 1266px;\n");
      out.write("	}\n");
      out.write("</style>\n");
      out.write("<body>\n");
      out.write("	");
      out.write("\n");
      out.write("		<header class=\"adminHeaderWrapper\">\n");
      out.write("			<div class=\"adminHeaderContaniner\">\n");
      out.write("				<h4 class=\"headerLogo\">\n");
      out.write("					<a href=\"home.jsp\" class=\"headerLogo purple\">\n");
      out.write("					<span ><img src=\"resources/images/logo1.png\"></span>\n");
      out.write("					</a>\n");
      out.write("				</h4>\n");
      out.write("				<h8 class=\"adminHeaderTitle\">사이트 관리자</h8>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"headerUtil\">\n");
      out.write("	            <button type=\"button\" class=\"myPageBtn\" onclick=\"javascript:location.href='siteAdminHome.jsp'\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ loginUsers.user_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님</button>\n");
      out.write("				<button type=\"button\" class=\"noneBtn\" onclick=\"javascript:location.href='logout.do'\">로그아웃</button>\n");
      out.write("			</div>\n");
      out.write("		</header>\n");
      out.write("	\n");
      out.write("		");
      out.write("\n");
      out.write("	<div class=\"adminContainerWrapper\">\n");
      out.write("		<div class=\"adminContainerLeft\">\n");
      out.write("			<ul class=\"adminLeftMenu\">\n");
      out.write("				<li class=\"adminMenuItem\"><a href=\"siteAdminHome.jsp\">MAIN&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a></li>\n");
      out.write("				<li class=\"adminMenuItem\"><a href=\"getUserList.do\">회원관리</a></li>\n");
      out.write("				<li class=\"adminMenuItem\"><a href=\"getProj.do\">프로젝트관리</a></li>\n");
      out.write("				<li class=\"adminMenuItem\"><a href=\"adminSalesManage.jsp\">매출관리</a></li>\n");
      out.write("				<li class=\"adminMenuItem\"><a href=\"notice.do\">FAQ / 공지</a></li>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"adminContainerRightWrapper\">\n");
      out.write("			<div class=\"adminContainerRight\">\n");
      out.write("				<div class=\"adminContainerRight_top\">\n");
      out.write("					<div class=\"adminLocationArea\">\n");
      out.write("						<h8>MAIN</h8>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"adminContainerContent\">\n");
      out.write("						<div class=\"cntUser\">\n");
      out.write("							<ul class=\"cnt\">\n");
      out.write("								<li id=\"title\"># 회원현황</li>\n");
      out.write("								<li class=\"New\" style=\"margin-bottom: 10px;\">최근 가입한 회원 </li>\n");
      out.write("								<li class=\"Tot\" style=\"margin-bottom: 10px;\">총 회원 </li>\n");
      out.write("								<li class=\"Out\" style=\"margin-bottom: 10px;\">탈퇴한 회원 </li>\n");
      out.write("							</ul>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"cntProj\">\n");
      out.write("							<ul class=\"cnt\">\n");
      out.write("								<li id=\"title\"># 프로젝트 현황</li>\n");
      out.write("								<li class=\"endProj\" style=\"margin-bottom: 10px;\">완료된 펀딩 </li>\n");
      out.write("								<li class=\"waitProj\" style=\"margin-bottom: 10px;\">신청 펀딩 </li>\n");
      out.write("								<li class=\"ingProj\" style=\"margin-bottom: 10px;\">진행중 펀딩 </li>\n");
      out.write("							</ul>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"cntSales\">\n");
      out.write("							<ul class=\"cnt\">\n");
      out.write("								<li id=\"title\"># 매출현황</li>\n");
      out.write("								<li class=\"cntPayment\" style=\"margin-bottom: 10px;\">결제완료 </li>\n");
      out.write("								<li class=\"cntSale\" style=\"margin-bottom: 10px;\">최근(30일) 매출 </li>\n");
      out.write("								<li class=\"cntCancel\" style=\"margin-bottom: 10px;\">취소된 결제 </li>\n");
      out.write("							</ul>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("			  	</div>\n");
      out.write("			  	<div class=\"adminContainerRight_bottom\">\n");
      out.write("					<div class=\"todayBox\">\n");
      out.write("						<ul class=\"today\">\n");
      out.write("							<li class=\"todaytitle\">금일 매출 현황</li>\n");
      out.write("							<li class=\"todaySale\"></li>\n");
      out.write("							<li class=\"todayCnt\">금일 판매건수 </li>\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("					<br><div class=\"chartdiv\">\n");
      out.write("							<div class=\"all\">\n");
      out.write("								<p class=\"chartTitle\"># 월별 매출액</p>\n");
      out.write("								<canvas id=\"myChart\"></canvas>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					<div class=\"request\">\n");
      out.write("						<div class=\"reqProj\">\n");
      out.write("						<span id=\"title_box\">#신청중인 프로젝트</span>\n");
      out.write("						<ul class=\"requestProj\">\n");
      out.write("							<li class=\"listPro\">프로젝트 번호</li>\n");
      out.write("							<li class=\"listPro\" style=\"margin-right: 75px;\">현황</li>\n");
      out.write("							<li class=\"listPro\">제목</li>\n");
      out.write("						</ul>\n");
      out.write("						<ul class=\"requestProj margin_fake_data\">\n");
      out.write("							<li class=\"listPro\" style=\"margin-right: 75px; margin-left: 35px\">319</li>\n");
      out.write("							<li class=\"listPro\">신청</li>\n");
      out.write("							<li class=\"listPro\">아로마 테라피</li>\n");
      out.write("						</ul>\n");
      out.write("						<ul class=\"requestProj margin_fake_data\">\n");
      out.write("							<li class=\"listPro\" style=\"margin-right: 75px; margin-left: 35px\">318</li>\n");
      out.write("							<li class=\"listPro\">신청</li>\n");
      out.write("							<li class=\"listPro\">통원목 벽시계</li>\n");
      out.write("						</ul>\n");
      out.write("						<ul class=\"requestProj margin_fake_data\">\n");
      out.write("							<li class=\"listPro\" style=\"margin-right: 75px; margin-left: 35px\">317</li>\n");
      out.write("							<li class=\"listPro\">신청</li>\n");
      out.write("							<li class=\"listPro\">코코넛 토너</li>\n");
      out.write("						</ul>\n");
      out.write("						<ul class=\"requestProj margin_fake_data\">\n");
      out.write("							<li class=\"listPro\" style=\"margin-right: 75px; margin-left: 35px\">316</li>\n");
      out.write("							<li class=\"listPro\">신청</li>\n");
      out.write("							<li class=\"listPro\">찰랑샴푸</li>\n");
      out.write("						</ul>\n");
      out.write("						<ul class=\"requestProj margin_fake_data\">\n");
      out.write("							<li class=\"listPro\" style=\"margin-right: 75px; margin-left: 35px\">315</li>\n");
      out.write("							<li class=\"listPro\">신청</li>\n");
      out.write("							<li class=\"listPro\">황금 횃불화로</li>\n");
      out.write("						</ul>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("<!-- chart.js -->\n");
      out.write("	<script type=\"text/javascript\">\n");
      out.write("            var context = document\n");
      out.write("                .getElementById('myChart')\n");
      out.write("                .getContext('2d');\n");
      out.write("            var myChart = new Chart(context, {\n");
      out.write("                type: 'line', // 차트의 형태\n");
      out.write("                data: { // 차트에 들어갈 데이터\n");
      out.write("                    labels: [\n");
      out.write("                        //x 축\n");
      out.write("                        '5월','6월','7월','8월','9월','10월','11월'\n");
      out.write("                    ],\n");
      out.write("                    datasets: [\n");
      out.write("                        { //데이터\n");
      out.write("                            label: '매출액', //차트 제목\n");
      out.write("                            fill: true, // line 형태일 때, 선 안쪽을 채우는지 안채우는지\n");
      out.write("                            data: [\n");
      out.write("                                10,14,21,18,23,26,30 //x축 label에 대응되는 데이터 값\n");
      out.write("                            ],\n");
      out.write("                            backgroundColor: [\n");
      out.write("                                //색상\n");
      out.write("                                'rgba(255, 99, 132, 0.2)',\n");
      out.write("                                'rgba(54, 162, 235, 0.2)',\n");
      out.write("                                'rgba(255, 206, 86, 0.2)',\n");
      out.write("                                'rgba(75, 192, 192, 0.2)',\n");
      out.write("                                'rgba(153, 102, 255, 0.2)',\n");
      out.write("                                'rgba(255, 159, 64, 0.2)'\n");
      out.write("                            ],\n");
      out.write("                            borderColor: [\n");
      out.write("                                //경계선 색상\n");
      out.write("                                'rgba(255, 99, 132, 1)',\n");
      out.write("                                'rgba(54, 162, 235, 1)',\n");
      out.write("                                'rgba(255, 206, 86, 1)',\n");
      out.write("                                'rgba(75, 192, 192, 1)',\n");
      out.write("                                'rgba(153, 102, 255, 1)',\n");
      out.write("                                'rgba(255, 159, 64, 1)'\n");
      out.write("                            ],\n");
      out.write("                            borderWidth: 1 //경계선 굵기\n");
      out.write("                        }/* ,\n");
      out.write("                        {\n");
      out.write("                            label: 'test2',\n");
      out.write("                            fill: false,\n");
      out.write("                            data: [\n");
      out.write("                                8, 34, 12, 24\n");
      out.write("                            ],\n");
      out.write("                            backgroundColor: 'rgb(157, 109, 12)',\n");
      out.write("                            borderColor: 'rgb(157, 109, 12)'\n");
      out.write("                        } */\n");
      out.write("                    ]\n");
      out.write("                },\n");
      out.write("                options: {\n");
      out.write("                    scales: {\n");
      out.write("                        yAxes: [\n");
      out.write("                            {\n");
      out.write("                                ticks: {\n");
      out.write("                                    beginAtZero: true\n");
      out.write("                                }\n");
      out.write("                            }\n");
      out.write("                        ]\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("        </script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
